data_dir: data
results_dir: wav # output example ./data/IEMOCAP_asrbn-vq/wav

pipeline: asrbn
anon_suffix: !ref _<pipeline>_<modules[model_tag_version]>

datasets:
  - name: IEMOCAP_dev
    data: IEMOCAP_dev
  - name: IEMOCAP_test
    data: IEMOCAP_test
  - name: libri_dev
    data: libri_dev
    enrolls: [_enrolls]
    trials: [_trials_f, _trials_m]
  - name: libri_test
    data: libri_test
    enrolls: [_enrolls]
    trials: [_trials_f, _trials_m]
  - name: train-clean-360
    data: train-clean-360

modules:
  anon_suffix: !ref <anon_suffix>
  anon_level_random_per_utt:      [train-clean-360, IEMOCAP_test, IEMOCAP_dev, libri_dev, libri_test] # Overwrite anon_level_constant because above
  anon_level_constant:            [train-clean-360, IEMOCAP_test, IEMOCAP_dev, libri_dev, libri_test]
  target_constant_spkid: "6081" # For anon_level_constant, must be one of the training data (libriTTS)
  ### Many models can be found here: https://github.com/deep-privacy/SA-toolkit/releases
  ### Online demo here: https://huggingface.co/spaces/Champion/SA-toolkit
  # model_tag_version: "hifigan_bn_tdnnf_600h_aug_v1" # NO VQ
  # model_tag_version: "hifigan_bn_tdnnf_wav2vec2_100h_aug_v1" # NO VQ
  # model_tag_version: "hifigan_bn_tdnnf_600h_vq_48_v1"   # This is B6
  model_tag_version: "hifigan_bn_tdnnf_wav2vec2_vq_48_v1" # This is B5
  device: "cuda"
  batch_size: 8 # works with GPU < 12Gib
